/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemafinanceiro;

import javax.swing.JLabel;

/**
 *
 * @author douglas
 */
public class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    
    public Tela_Principal() {
        setResizable(false);
        initComponents();
        
        DAOValores v = new DAOValores();
        float entrada;     
        entrada = v.soma("entrada");
        l_entrada.setText(String.valueOf(entrada)+" R$");
        
        float saida = v.soma("saida");
        l_saida.setText(String.valueOf(saida)+" R$");
        
        l_caixa.setText(String.valueOf(entrada-saida)+" R$");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_saida = new javax.swing.JButton();
        bt_entrada = new javax.swing.JButton();
        l_entrada_mes = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bt_relatorio = new javax.swing.JButton();
        l_saida_mes = new javax.swing.JLabel();
        l_valor_caixa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_saida.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        bt_saida.setText("ADICIONAR SAÍDA");
        bt_saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saidaActionPerformed(evt);
            }
        });

        bt_entrada.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        bt_entrada.setText("ADICIONAR ENTRADA");
        bt_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entradaActionPerformed(evt);
            }
        });

        l_entrada_mes.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        l_entrada_mes.setText("ENTRADA DO MÊS");

        bt_relatorio.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        bt_relatorio.setText("GERAR RELATÓRIO");
        bt_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_relatorioActionPerformed(evt);
            }
        });

        l_saida.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        l_saida.setText("0,0 R$");

        l_entrada.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        l_entrada.setText("0,0 R$");

        l_saida_mes.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        l_saida_mes.setText("SAÍDA DO MÊS");

        l_caixa.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        l_caixa.setText("0,0 R$");

        l_valor_caixa.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        l_valor_caixa.setText("VALOR EM CAIXA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l_entrada_mes)
                            .addComponent(l_entrada)
                            .addComponent(bt_entrada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bt_saida)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(l_saida_mes)
                                    .addComponent(l_saida))
                                .addGap(60, 60, 60))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_valor_caixa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l_caixa))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bt_relatorio)))
                        .addGap(53, 53, 53)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_caixa)
                    .addComponent(l_valor_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_relatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_entrada_mes)
                    .addComponent(l_saida_mes))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_saida)
                    .addComponent(l_entrada))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_saida)
                    .addComponent(bt_entrada))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_saidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saidaActionPerformed
        new Adicionar_Saida().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_saidaActionPerformed

    private void bt_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entradaActionPerformed
        new Adicionar_Entrada().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_entradaActionPerformed

    private void bt_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_relatorioActionPerformed
        new Relatorio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_relatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_entrada;
    private javax.swing.JButton bt_relatorio;
    private javax.swing.JButton bt_saida;
    private javax.swing.JSeparator jSeparator1;
    private static final transient javax.swing.JLabel l_caixa = new javax.swing.JLabel();
    private static final transient javax.swing.JLabel l_entrada = new javax.swing.JLabel();
    private javax.swing.JLabel l_entrada_mes;
    private static final transient javax.swing.JLabel l_saida = new javax.swing.JLabel();
    private javax.swing.JLabel l_saida_mes;
    private javax.swing.JLabel l_valor_caixa;
    // End of variables declaration//GEN-END:variables
}
